[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vibprep"
version = "0.1.0"
description = "Modular preprocessing library for vibrational spectroscopy (FTIR, Raman)"
readme = "README.md"
requires-python = ">=3.9"

authors = [
  { name = "Alejandro Leonardo García Navarro" }
]

license = "MIT"
license-files = ["LICENSE"]

keywords = [
  "spectroscopy",
  "vibrational spectroscopy",
  "FTIR",
  "Raman",
  "preprocessing",
  "baseline correction",
  "chemometrics",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
  "numpy>=1.22",
  "scipy>=1.8",
  "pandas>=1.4",
  "pybaselines>=1.0"
]

[project.urls]
Homepage = "https://github.com/alexgaarciia/VibPrep"
Repository = "https://github.com/alexgaarciia/VibPrep"
Issues = "https://github.com/alexgaarciia/VibPrep/issues"

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "ruff"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
